### ISSUE TITLE
Script issue-ecr.sh incompatible with recent versions of keripy

### ISSUE THREAD

**Issue by lenkan** [WebOfTrust/signifypy#92]
# Description

I tried to run the issue-ecr.sh script on the development branch. Currently, it uses `kli vc issue` and `kli vc accept`, but these commands has been removed from the KLI, see https://github.com/WebOfTrust/keripy/commit/c390d904a809d1c8b6ec0e6acbfa6201e55caa9c.

See references the commands here https://github.com/WebOfTrust/signifypy/blob/c48847dfe09c0f3e6901e55e0085c62e12859fd3/scripts/issue-ecr.sh#L52

Currently, signifypy does not pin a version or commit of keripy in its dependencies, see https://github.com/WebOfTrust/signifypy/blob/development/setup.py#L68.

So when I do `pip install -r requirements.txt`, I get the latest version of keripy (kli) without `kli vc issue` and `kli vc accept`.

# Expected result

./scripts/issue-ecr.sh works

# Actual result

./scripts/issue-ecr.sh fails due to missing `kli vc accept`

**Comment by pfeairheller** [comment]
I have a fix for this.  I'll submit a PR later today.

**Comment by lenkan** [comment]
This was solved in #93
